apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-single-env
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      env:
        - name: CONNECTION_MAX
          valueFrom:
            configMapKeyRef:
              name: sample-configmap
              key: connection.max
        - name: NGINX_CONF
          valueFrom:
            configMapKeyRef:
              name: sample-configmap
              key: nginx.conf
