apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
data:
  thread: '16'
  connection.max: '100'
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log
    pid /run/nginx/pid
  test.sh: |
    #! /bin/bash
    echo 'hello, kubernetes'
    sleep infinity
