apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      volumeMounts:
        - name: nginx-pvc
          mountPath: /nginx
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: sample-pvc
