apiVersion: v1
kind: Pod
metadata:
  name: sample-hostpath
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: config-volume
          mountPath: /srv
  volumes:
    - name: config-volume
      hostPath:
        path: /etc
        type: Directory
