apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-pv-readonlymany
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      - maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16
          volumeMounts:
            - name: nginx-pvc
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: sample-pvc
            readOnly: true
