apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-single-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      volumeMounts:
        - name: volume-config
          mountPath: /config
  volumes:
    - name: volume-config
      configMap:
        name: sample-configmap
        items:
          - key: nginx.conf
            path: nginx-sample.conf
          - key: thread
            path: thread.txt
