apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-resize
spec:
  storageClassName: sample-storageclass-resize
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-resize-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      volumeMounts:
        - name: nginx-pvc
          mountPath: /usr/share/nginx/index.html
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: sample-storageclass-resize
