apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-multi-env
spec:
  containers:
    - name: secret-container
      image: nginx:1.16
      env:
        - name: DB_USERNAME
          valueFrom:
            secretRef:
              name: sample-db-auth
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretRef:
              name: sample-db-auth
              key: password
