apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-publish-notready
spec:
  serviceName: sample-publish-notready
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: amsy810/echo-nginx:v2.0
          readinessProbe:
            exec:
              command: ['sh', '-c', 'exit 1']

---
apiVersion: v1
kind: Service
metadata:
  name: sample-publish-notready
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: sample-app
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 80
  publishNotReadyAddresses: true
