apiVersion: v1
kind: Pod
metadata:
  name: sample-termination
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      lifecycle:
        preStop:
          exec:
            command: ['sh', '-c', 'sleep 10'] # Serviceから除外されるまでの時間
  terminationGracePeriodSeconds: 30
