apiVersion: v1
kind: Pod
metadata:
  name: sample-ephemeral-storage-multi
spec:
  containers:
    - name: container-a
      image: amsy810/tools:v2.0
      resources:
        requests:
          ephemeral-storage: 1024Mi
        limits:
          ephemeral-storage: 2048Mi
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
    - name: container-b
      image: amsy810/tools:v2.0
      resources:
        requests:
          ephemeral-storage: 1024Mi
        limits:
          ephemeral-storage: 2048Mi
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
