apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limitrange-pod
  namespace: default
spec:
  limits:
    - type: Pod
      max:
        cpu: 2000m
        memory: 2048Mi
      min:
        cpu: 128m
        memory: 125Mi
      maxLimitRequestRatio:
        cpu: 2
        memory: 2
