apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-resource
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 200
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              memory: 2048Mi
              cpu: 1000m
