apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-vpa-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: vpa-container
          image: amsy810/tools:v2.0
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
        - name: no-vpa-container
          image: amsy810/tools:v2.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: vpa-service
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 80
