apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
    annotation1: val
    annotation2: '100'
  labels:
    app: sample-app
spec:
  containers:
    - name: nginx
      image: nginx:1.17
