apiVersion: v1
kind: Service
metadata:
  name: sample-service-topology
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - name: 'http-port'
      protocol: TCP
      port: 8080
      targetPort: 80
  # topologyKeys:
  #   - kubernetes.io/hostname
  #   - '*'
