apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport-local
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - name: 'http-port'
      port: 8080
      targetPort: 80
      nodePort: 30080
  externalTrafficPolicy: Local
