apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: sample-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.21.200.0/24
  autoAssign: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: sample-lb
spec:
  ipAddressPools:
    - sample-pool
