apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 172.21.0.5
    - 172.21.0.4
    - 172.21.0.2
  selector:
    app: sample-app
  ports:
    - name: 'http-port'
      protocol: TCP
      port: 8080
      targetPort: 80
