apiVersion: v1
kind: Service
metadata:
  name: sample-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: sample-app
  ports:
    - name: 'http-port'
      port: 8080
      targetPort: 80
      protocol: TCP
