apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  clusterIP: 10.96.100.100
  selector:
    app: sample-app
  ports:
    - name: 'http-port'
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: 'https-port'
      protocol: TCP
      port: 8443
      targetPort: 443
