apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: tools-container
      image: amsy810/tools:v2.0
      command: ['sleep']
      args: ['10000000000000000000']
  restartPolicy: Never
