apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-affinity-zone-host
spec:
  containers:
    - name: nginx
      image: nginx:1.16
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: Exists
          topologyKey: topology.kubernetes.io/zone
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: Exists
            topologyKey: kubernetes.io/hostname
