apiVersion: batch/v1
kind: Job
metadata:
  name: sample-paralleljob
spec:
  completions: 10
  parallelism: 2
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: tools-container
          image: ubuntu:22.04
          command: ['sleep']
          args: ['10']
      restartPolicy: Never
