apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: tools-container
          image: ubuntu:22.04
          command: ['sh', '-c']
          args: ['$(sleep 3600)']
      restartPolicy: OnFailure
