apiVersion: batch/v1
kind: Job
metadata:
  name: sample-multi-workqueue-job
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 3
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: tools-container
          image: ubuntu:22.04
          command: ['sleep']
          args: ['10']
      restartPolicy: Never
