apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset-ondelete
spec:
  serviceName: sample-stateful-ondelete
  updateStrategy:
    type: OnDelete
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
