apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  hostNetwork: true
  containers:
    - name: nginx-container
      image: nginx:1.16
      command: ['/bin/sleep']
      args: ['3600']
      workingDir: /tmp
  hostAliases:
    - ip: 8.8.8.8
      hostnames:
        - google-dns
